Py3 only
farsightsec/pymtbl pull request #13
Opened 2022-02-09 20:05 UTC by alesage

2022-02-09 20:08 UTC, djw1149 commented
building on debian stretch warns:
```
$ python3 setup.py build check
...
running check
warning: check: missing required meta-data: url

warning: check: missing meta-data: either (author and author_email) or (maintainer and maintainer_email) must be supplied
```

2022-02-09 20:28 UTC, djw1149 approved these changes

2022-02-09 20:48 UTC, reedjc requested changes
Due to source change (setup.py), please bump version (like 0.5.1) in setup.py and debian/changelog

2022-02-11 00:31 UTC, reedjc approved these changes
This looks good to me. I saw the successful debian builds and my centos build after my spec changes.

2022-02-11 00:32 UTC, merged